cookie:
  expiry_days: 30
  key: random_signature_key
  name: yafa_cookie_name
credentials:
  usernames:
    demo:
      email: demo@email.com
      logged_in: false
      name: Demo
      password: $2b$12$pNoruaS0.nhOAL57JyS8/OZ0piroo/7WQ5nK7eyef5L1oMJ1Bmh9i
    jsmith:
      email: jsmith@gmail.com
      logged_in: false
      name: John Smith
      password: $2b$12$BsOVEoSgqwEfkFrfImlfl.xFwbBy3lZ0C0l3EMBJrFNy86n6Lf6ui
    prithvi:
      email: prithvi@gmail.com
      logged_in: false
      name: Prithviraj More
      password: $2b$12$oWrHp2iXlz3QRkaZWQUnHu42U4ABMBFx9quNFT0op3YBMlOd4IdTW
    pspiagicw:
      email: prathampowar2001@gmail.com
      logged_in: true
      name: Pratham Powar
      password: $2b$12$h8yajXIkZA3HN5UEzmy2Su0bFKhLZTHf9u.9X5O7la7hunVBIKCtm
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$17klx1Ll83rTz0iAjSts..2V84yES5J8RPE/JGfoWae.5tapnF99G
preauthorized:
  emails:
  - melsby@gmail.com
