[client]
showSidebarNavigation = false

[theme] # You have to add this line
base = "light"

# primaryColor = '#00ff00' # Bright Orange
#
# backgroundColor = '#000000' # Dark Blue
#
# secondaryBackgroundColor = '#86c' # Lighter Blue
